name: Deploy frontend to firebase
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn 

      - name: Build frontend
        run: yarn build

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.2.2
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          REACT_APP_FIREBASE_REACT_APP_POKEAPI: ${{ secrets.POKEAPI }}

      